### PR TITLE
[Feature] Favorite

### PR DESCRIPTION
**Pull request by jonnii**

### CODE REVIEW

**Comment by jonnii** [comment]
I want to wait for the changes https://github.com/gothinkster/ember-realworld/pull/12 to land, then I'll rebase on top of that and add the tests. What are your thoughts as to where to put the call to the favorite endpoint (https://github.com/gothinkster/realworld/tree/master/api#favorite-article)? Ember-data doesn't have a good story around where to put "actions", so options are:

1. Create a favorite model (awkward because endpoint returns article)
2. Add methods on the article itself `article.favorite()`
3. Create a service `articleService.favorite(article)`

My preference would be for (3) because it means you can have methods which don't require an article instance (e.g. `articleService.favoriteBySlug(article.slug)`...).

**Comment by jonnii** [comment]
One other thing I found surprising was this:

```
          {{feed-item 
            imageSrc=article.author.image 
            author=article.author.username 
            date=article.createdAt
            hearts=article.favoritesCount
            content=article.body}}
```

In this case I think it's _ok_ to copy the attributes you care about but it's kind of awkward to change the names, e.g. I saw `hearts` in the template and had to go figure out what the upstream property was...

**Comment by Alonski** [comment]
Also @jonnii As you can see the automated tests on Travis failed because of syntax errors.
Please run yarn lint:fix before pushing.
@alexlafroscia Maybe we could setup automatic git commit hooks for this?
At work I use SVN so maybe you can set this up?

**Comment by alexlafroscia** [comment]
You can set up git hooks, but they're only client side and they aren't actually stored as part of the repo.  We'd each have to add the hooks ourselves.  I've already done this for my own local config, to run the tests before each commit.

**Comment by jonnii** [comment]
@Alonski i won't be able to fix the linting until I have everything wired up...

**Comment by jonnii** [comment]
@alexlafroscia @Alonski I've wired up the favorite action, still needs to handle things like not being authenticated and perhaps showing an error if favoriting fails, but should show roughly how things would look. thoughts?

**Comment by alexlafroscia** [comment]
Looks good to me, but we should flesh out the tests before merging.

**Comment by Alonski** [comment]
Hey @jonnii Want to rebase this with master and get tests passing so we can merge this in?

**Comment by jonnii** [comment]
@Alonski can do tonight! i'll wire up the endpoints too.

**Comment by Alonski** [comment]
@jonnii Hey whats up man? Think you can take a look at this again?

**Comment by jonnii** [comment]
Been a crazy week, hopefully will get time soon!

**Comment by Alonski** [comment]
Yea I hear you 😅 
Working on this every few days for fun and want to get this to v1 
Whenever you can is good.
BTW I copied your code here for User Follow / Unfollow 😄

**Comment by Alonski** [comment]
Closing... Its been a long time :) Thanks for all the help!

**Pull request closed without merging**
